@baseUrl = http://localhost:5001/api

POST {{baseUrl}}/player/create
Content-Type: application/json

{
  "nickname": "Player1092",
  "country": "TR"
}

###

GET {{baseUrl}}/player

###

GET {{baseUrl}}/player/1

###

PUT {{baseUrl}}/player/1
Content-Type: application/json

{
  "nickname": "Player1092",
  "country": "TR"
}

###

DELETE {{baseUrl}}/player/1